## allow network connection
quarkus.http.host=0.0.0.0

## datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=xxx
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/document-ingestion-db

## flyway
quarkus.flyway.migrate-at-start=true

## ollama
ollama.base-url=http://100.87.153.22:11434
ollama.model-name=gemma4:e2b
ollama.embedding-model-name=bge-m3
#ollama.model-name=gemma4:26b
ollama.num-ctx=65536
ollama.timeout-seconds=300



## langchain4j loggin
com.chriswininger.model.request-logging=true 
quarkus.log.category."dev.langchain4j".level=DEBUG
quarkus.log.category."dev.langchain4j".min-level=DEBUG
quarkus.log.category."dev.langchain4j.service".level=DEBUG
quarkus.log.category."dev.langchain4j.service".min-level=DEBUG
quarkus.log.category."java.net.http".level=DEBUG
quarkus.log.category."java.net.http".min-level=DEBUG
quarkus.log.category."jdk.internal.net.http".level=DEBUG
quarkus.log.category."jdk.internal.net.http".min-level=DEBUG

## openapi spec generation
quarkus.smallrye-openapi.store-schema-directory=../openapi-specs
quarkus.smallrye-openapi.open-api-version=3.0.3

## test profile overrides
%test.quarkus.flyway.migrate-at-start=false
