## allow network connection
quarkus.http.host=0.0.0.0

## datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=xxx
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/document-ingestion-db

## flyway
quarkus.flyway.migrate-at-start=true

## ollama
ollama.base-url=http://100.87.153.22:11434

ollama.embedding-model-name=bge-m3

#ollama.model-name=gemma4:e4b
#ollama.num-ctx=32768

ollama.model-name=gemma4:e2b
ollama.num-ctx=65536

ollama.timeout-seconds=300

## toc isolation (ollama cloud)
#https://ollama.com | http://100.87.153.22:11434
ollama.toc-isolation.base-url=https://ollama.com
ollama.toc-isolation.api-key=${OLLAMA_API_KEY:}
#ollama.toc-isolation.base-url=http://100.87.153.22:11434
ollama.toc-isolation.model-name=minimax-m2.7
# nemotron-3.5-lightning -- Real Bad Just span forever on first one
# minimax-m2.7
# real badttempvnn/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-Q4-K-M
# can't even finish so slow gemma4:12b
# try next ollama run ttempvnn/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-Q4-K-M
#qwen3.8

# qwen3.5: taking around 19 min across all tests much slower than kimi-k3 which is more like 7 minutes
# qwen3.8: only available on local

# deepseek-v4-flash
# Also works well (cloud only)


# kimi-k2.7-code
# very fast but wrong a lot

# works for TOC ISOLATION
#glm-5.1 (cloud only):
#  Works well, best so far;
#  Over 700 bill params;
#  1:18 mm:ss max run time
#  Usage: high
# Failed on one book with thinking off, but was much faster
# Correction, did work well, then suddenly started failing pretty often

# glm-5.2 (cloud only)
# Now working as well as glm-5.1 used to work

# gemma4:31b:
#   works
#   Slower than glm-5.1 even on cloud, burns more tokens

# qwen3.5 (cloud model, but not sure what params; probably 122)
# worked (with think on; fails with it off)
# extremely slow more than 5 minutes


# 'qwen3.5:27b'
#   Not available on their cloud



# gemma4:26b works
# gemma4:12b worked and fit in gpu but was somehow super slow, maybe because of thinking
# yep turning off think made it way faster but fail
ollama.toc-isolation.num-ctx=65536



## langchain4j loggin
com.chriswininger.model.request-logging=true 
quarkus.log.category."dev.langchain4j".level=DEBUG
quarkus.log.category."dev.langchain4j".min-level=DEBUG
quarkus.log.category."dev.langchain4j.service".level=DEBUG
quarkus.log.category."dev.langchain4j.service".min-level=DEBUG
quarkus.log.category."java.net.http".level=DEBUG
quarkus.log.category."java.net.http".min-level=DEBUG
quarkus.log.category."jdk.internal.net.http".level=DEBUG
quarkus.log.category."jdk.internal.net.http".min-level=DEBUG

## openapi spec generation
quarkus.smallrye-openapi.store-schema-directory=../openapi-specs
quarkus.smallrye-openapi.open-api-version=3.0.3

## test profile overrides
%test.quarkus.flyway.migrate-at-start=false
