## allow netowork connection
quarkus.http.host=0.0.0.0

## datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=xxx
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/spring-ai-demo-db

## flyway
quarkus.flyway.migrate-at-start=true

## ollama
ollama.base-url=http://100.87.153.22:11434
#ollama.model-name=gemma4:e2b
ollama.model-name=gemma4:26b
ollama.timeout-seconds=300

## test profile overrides
%test.quarkus.flyway.migrate-at-start=false
